name: validate-files

on:
  push:
    branches: [rido/*]

  pull_request:
    branches: [main]
    paths:
      - 'dtmi/**'

jobs:
  validate-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: files
        uses: jitterbit/get-changed-files@v1

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: npm install
        run: npm install --production

      - name: check DTMI path convention
        run: node .github/workflows/validate-files.js ${{steps.files.outputs.added_modified}}

      - name: check global IDs 
        run: node .github/workflows/validate-ids.js ${{steps.files.outputs.added_modified}}

      - name: check dependencies 
        run: node .github/workflows/validate-deps.js ${{steps.files.outputs.added_modified}}
